# Generated by Django 3.1.7 on 2021-03-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVShowApp', '0003_belonging_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belonging',
            name='name',
        ),
    ]
