# Generated by Django 3.1.7 on 2021-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVShowApp', '0004_remove_belonging_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
