# Generated by Django 3.1.7 on 2021-03-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVShowApp', '0005_show_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='slug',
        ),
    ]
